root: true

extends: 'eslint:recommended'

parserOptions:
  ecmaVersion: 5

env:
  node: true

rules:
  brace-style:
    - error
    - allman
  comma-dangle:
    - error
    - always-multiline
  curly:
    - error
  eqeqeq:
    - error
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always